services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
  backend:
    image: 'ghcr.io/nilshartmann/tanstack-router-demo-backend:latest'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'GENERATE_OPEN_API_DOC_ON_STARTUP_ENABLED=false'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
