-- Feedback for Recipes 1 to 90
INSERT INTO feedbacks (rating, comment, created_at, recipe_id, commenter)
VALUES (5, 'This recipe is a game-changer! The flavors are incredible, and the instructions are easy to follow.',
        '2023-09-30', 1, 'Alice Johnson'),
       (4, 'Tasty and quick! I added some extra herbs for a personal touch. Definitely a go-to recipe.', '2023-10-10',
        2,
        'Bob Smith'),
       (3, 'Decent, but I felt it needed more seasoning. Will try tweaking the spices next time.', '2023-10-20', 3,
        'Charlie Davis'),
       (5, 'Absolutely loved it! The combination of ingredients is perfect. Will make this again for sure.',
        '2023-10-30',
        4, 'David Brown'),
       (4, 'Simple and delicious. I substituted a few ingredients, and it turned out great.', '2023-11-10', 5,
        'Eva White'),
       (2, 'Not my favorite. The flavors didn''t suit my taste buds. Might try a different recipe next time.',
        '2023-11-20', 6, 'Frank Black'),
       (5, 'Excellent! The step-by-step guide made it foolproof. Can''t wait to explore more recipes.', '2023-11-30', 7,
        'Grace Miller'),
       (3, 'Good, but I found it a bit too salty. Adjusted the seasoning, and it improved.', '2023-12-10', 8,
        'Harry Wilson'),
       (5, 'Family favorite! Everyone asked for seconds. This recipe is now in our regular rotation.', '2023-12-20', 9,
        'Ivy Turner'),
       (4, 'Solid recipe. I appreciate the versatility. Will try different variations in the future.', '2023-12-30', 10,
        'Jack Young'),
       (3, 'Nice, but I felt it lacked a bit of spice. Added chili flakes for an extra kick.', '2024-01-10', 11,
        'Karen Taylor'),
       (4, 'Great flavor combo! I added a touch of hot sauce for some heat. Will make again.', '2024-01-20', 12,
        'Larry Anderson'),
       (5, 'Outstanding! The quinoa adds a wonderful texture. Shared the recipe with friends.', '2024-01-30', 13,
        'Megan Martinez'),
       (3, 'Decided to grill the shrimp. It added a smoky flavor. A hit at the dinner table.', '2024-02-10', 14,
        'Nathan Perez'),
       (2, 'Not a fan of the raspberry-chocolate combo. Personal preference, I suppose.', '2024-02-20', 15,
        'Olivia Hernandez'),
       (5, 'Loved the noodle dish! Added extra veggies for a nutritious twist. Excited to try more.', '2024-02-29', 16,
        'Paula Bailey'),
       (4, 'Taco night is now a family tradition! The simplicity and freshness are a winning combo.', '2024-03-10', 17,
        'Quincy King'),
       (3, 'Muffins turned out a bit dry. Adjusted the baking time. Next time, I''ll try variations.', '2024-03-20', 18,
        'Rachel Cooper'),
       (5, 'Experimented with cheeses. Feta added a nice tang to the salad. A go-to recipe now.', '2024-03-30', 19,
        'Samuel Fisher'),
       (4, 'Can''t get enough of this pasta dish! The garlic butter sauce is heavenly. Family-approved.', '2024-04-10',
        20,
        'Tina Reed'),
       (4, 'Spaghetti Carbonara with a twist! The pancetta takes it to another level. A new favorite.', '2024-04-20',
        21,
        'Ulysses Turner'),
       (5, 'Sweet and savory chicken skewers. The marinade is the secret to its deliciousness.', '2024-04-30', 22,
        'Vivian Adams'),
       (3, 'Coconut curry soup with a kick. Adjusted the spice level based on preference.', '2024-05-10', 23,
        'Walter Mitchell'),
       (5, 'Homemade pizza with a crispy crust. Customized the toppings for a perfect pizza.', '2024-05-20', 24,
        'Ximena Sanchez'),
       (4, 'Refreshing mango salsa. Perfect for summer gatherings. Pairs well with grilled dishes.', '2024-05-30', 25,
        'Yasmine Carter'),
       (2, 'Not a fan of zucchini noodles. May substitute with regular pasta next time.', '2024-06-10', 26,
        'Zachary Wood'),
       (5, 'Crispy garlic parmesan chicken wings. A crowd-pleaser for game nights and parties.', '2024-06-20', 27,
        'Abigail Reed'),
       (4, 'Lemon herb quinoa salad. A light and nutritious option for lunch or a side dish.', '2024-06-30', 28,
        'Benjamin Robinson'),
       (3, 'Savory mushroom risotto. Requires patience but worth it for the rich flavors.', '2024-07-10', 29,
        'Charlotte Green'),
       (5, 'Chocolate chip banana bread. A classic recipe with a hint of cinnamon for warmth.', '2024-07-20', 30,
        'Daniel Flores'),
       (4, 'Delicious! The lentil soup is hearty and satisfying. Perfect for a cozy evening.', '2024-07-31', 31,
        'Alice Johnson'),
       (5, 'Cajun-spiced shrimp pasta is a winner! The spices are just right, and it''s so flavorful.', '2024-08-10',
        32,
        'Bob Smith'),
       (3, 'Homestyle chicken pot pie is comfort food at its best. Loved the golden crust!', '2024-08-20', 33,
        'Charlie Davis'),
       (5, 'Mediterranean chickpea salad is a burst of colors. So fresh and vibrant!', '2024-08-30', 34, 'David Brown'),
       (4, 'Teriyaki glazed salmon is a quick and delicious option. Perfect for a busy day.', '2024-09-10', 35,
        'Eva White'),
       (2, 'Avocado toast with a twist is a creative breakfast idea. Loved experimenting with toppings.', '2024-09-20',
        36,
        'Frank Black'),
       (5, 'BBQ pulled pork sliders are a hit! Great for gatherings and picnics.', '2024-09-30', 37, 'Grace Miller'),
       (4, 'Caprese bruschetta is an elegant appetizer. The flavors are fresh and delightful.', '2024-10-10', 38,
        'Harry Wilson'),
       (3, 'Creamy spinach and artichoke dip is a crowd-pleaser. Perfect for social gatherings.', '2024-10-20', 39,
        'Ivy Turner'),
       (5, 'Stuffed bell peppers with quinoa are a healthy and tasty dinner option.', '2024-10-30', 40, 'Jack Young'),
       (4, 'Lemon garlic herb chicken is zesty and aromatic. A delightful dish!', '2024-11-10', 41, 'Karen Taylor'),
       (5, 'Eggplant Parmesan has layers of perfection. A savory delight!', '2024-11-20', 42, 'Larry Anderson'),
       (3, 'Chocolate avocado mousse is guilt-free indulgence. Creamy and rich in chocolate flavor.', '2024-11-30', 43,
        'Megan Martinez'),
       (5, 'Homemade gnocchi with sage butter is a soft and pillowy delight. Loved the flavors!', '2024-12-10', 44,
        'Nathan Perez'),
       (4, 'Thai coconut curry is fragrant and spicy. Captures the essence of Thai cuisine.', '2024-12-20', 45,
        'Olivia Hernandez'),
       (2, 'Quinoa-stuffed acorn squash is a wholesome option for fall. Loved the balance of flavors.', '2024-12-30',
        46,
        'Paula Bailey'),
       (5, 'Crispy buffalo cauliflower bites are a vegetarian delight. Great alternative to wings!', '2025-01-10', 47,
        'Quincy King'),
       (4, 'Tomato basil mozzarella skewers are an elegant appetizer. Perfect for gatherings.', '2025-01-20', 48,
        'Rachel Cooper'),
       (3, 'Sweet potato and black bean chili is a hearty vegetarian option. Perfect for chilly days.', '2025-01-30',
        49,
        'Samuel Fisher'),
       (5, 'Balsamic glazed Brussels sprouts are caramelized and tangy. A delicious side dish!', '2025-02-10', 50,
        'Tina Reed'),
       (4, 'Chia seed pudding with berries is a nutritious and tasty breakfast or dessert.', '2025-02-20', 51,
        'Ulysses Turner'),
       (5, 'Honey mustard glazed chicken thighs are succulent and flavorful. A weeknight favorite!', '2025-02-28', 52,
        'Vivian Adams'),
       (3, 'Mango pineapple salsa is a tropical and refreshing condiment. Great with grilled dishes.', '2025-03-10', 53,
        'Walter Mitchell'),
       (5, 'Roasted vegetable quiche is a versatile dish for breakfast, brunch, or lunch.', '2025-03-20', 54,
        'Ximena Sanchez'),
       (4, 'Pesto pasta with sun-dried tomatoes is quick and flavorful. Loved the vibrant ingredients.', '2025-03-30',
        55,
        'Yasmine Carter'),
       (2, 'Butternut squash soup with a hint of cinnamon is a comforting and autumn-inspired soup.', '2025-04-10', 56,
        'Zachary Wood'),
       (5, 'Blueberry almond overnight oats are a convenient and nutritious breakfast option.', '2025-04-20', 57,
        'Abigail Reed'),
       (4, 'Garlic butter shrimp linguine is a savory and satisfying pasta dish. Easy to prepare!', '2025-04-30', 58,
        'Benjamin Robinson'),
       (3, 'Baked sweet potato fries are a healthier alternative to traditional fries. Delicious flavor!', '2025-05-10',
        59, 'Charlotte Green'),
       (5, 'Lemon raspberry cheesecake bars are creamy and tangy. A delightful treat for dessert lovers.', '2025-05-20',
        60, 'Daniel Flores'),
       (4, 'Savory stuffed mushrooms are a delightful appetizer. Perfect for dinner parties!', '2025-05-30', 91,
        'Ella Lewis'),
       (5, 'Maple-glazed salmon is a sweet and savory treat. Loved the unique flavor profile.', '2025-06-10', 92,
        'Finn Turner'),
       (3, 'Quinoa and black bean salad is a refreshing and protein-packed dish. Great for lunch.', '2025-06-20', 93,
        'Gabriel Turner'),
       (5, 'Gourmet grilled cheese with a twist! The addition of caramelized onions is genius.', '2025-06-30', 94,
        'Hazel Turner'),
       (4, 'Roasted red pepper hummus is a classic dip with a kick. Perfect with pita chips!', '2025-07-10', 95,
        'Isaac Turner'),
       (2, 'Not a fan of the cauliflower pizza crust. Prefer the traditional crust texture.', '2025-07-20', 96,
        'Jasmine Turner'),
       (5, 'Creamy mushroom and spinach risotto is a comfort dish with a touch of elegance.', '2025-07-30', 97,
        'Kai Turner'),
       (4, 'Pumpkin spice muffins are a fall-inspired treat. The aroma is intoxicating!', '2025-08-10', 98,
        'Liam Turner'),
       (3, 'Southwest quinoa bowl is a colorful and nutritious meal. Loved the mix of flavors.', '2025-08-20', 99,
        'Mia Turner'),
       (5, 'Lemon pepper chicken wings are a crowd-pleaser. Perfect for game day gatherings.', '2025-08-30', 100,
        'Noah Turner'),
       (4, 'Ginger soy glazed tofu is a flavorful vegetarian option. Great with stir-fried veggies!', '2025-09-10', 101,
        'Olivia Turner'),
       (5, 'Baked apple cinnamon oatmeal is a warm and comforting breakfast choice.', '2025-09-20', 102,
        'Parker Turner'),
       (3, 'Mediterranean quinoa stuffed peppers are a light and healthy dinner option.', '2025-09-30', 103,
        'Quinn Turner'),
       (5, 'Spicy garlic shrimp skewers are perfect for seafood lovers. A burst of flavors!', '2025-10-10', 104,
        'Riley Turner'),
       (4, 'Berry spinach salad with balsamic vinaigrette is a refreshing and tangy delight.', '2025-10-20', 105,
        'Sofia Turner'),
       (2, 'Not a fan of the kale smoothie. The bitterness was a bit overwhelming for my taste.', '2025-10-30', 106,
        'Tyler Turner'),
       (5, 'Homemade granola with mixed nuts is a crunchy and wholesome breakfast option.', '2025-11-10', 107,
        'Uma Turner'),
       (4, 'Cilantro lime chicken tacos are a zesty and flavorful choice for taco night.', '2025-11-20', 108,
        'Victor Turner'),
       (3, 'Cauliflower fried rice is a low-carb alternative. Enjoyed the variety of veggies!', '2025-11-30', 109,
        'Willa Turner'),
       (5, 'Vanilla bean panna cotta with berry compote is a sophisticated and sweet dessert.', '2025-12-10', 110,
        'Xander Turner'),
       (4, 'Sesame ginger tofu stir-fry is a delightful and savory dish. Loved the crunch!', '2025-12-20', 111,
        'Yara Turner'),
       (5, 'Blueberry lemon pancakes are a bright and fluffy breakfast option. A family favorite!', '2025-12-30', 112,
        'Zane Turner'),
       (3, 'Mango habanero chicken wings are a spicy and sweet combo. Perfect for parties!', '2026-01-10', 113,
        'Amelia Turner'),
       (5, 'Caprese-stuffed avocado is a refreshing and elegant appetizer. Loved the presentation.', '2026-01-20', 114,
        'Bryce Turner'),
       (4, 'Baked garlic parmesan potato wedges are a crispy and flavorful side dish.', '2026-01-30', 115,
        'Cora Turner'),
       (2, 'Not a fan of the Brussels sprouts. The flavor was too strong for my liking.', '2026-02-10', 116,
        'Dexter Turner'),
       (5, 'Peach and prosciutto flatbread is a sweet and savory treat. Great for brunch!', '2026-02-20', 117,
        'Elena Turner'),
       (4, 'Chickpea tikka masala is a vegetarian delight. The spices are well-balanced.', '2026-02-28', 118,
        'Felix Turner'),
       (3, 'Quinoa and vegetable stuffed mushrooms are a tasty and nutritious appetizer.', '2026-03-10', 119,
        'Grace Turner'),
       (5, 'Homemade raspberry sorbet is a refreshing and fruity dessert. Loved the natural sweetness.', '2026-03-20',
        120,
        'Henry Turner'),
       (5, 'Spinach and feta stuffed chicken breast is an elegant and flavorful main dish.', '2026-04-10', 122,
        'Jaxon Turner'),
       (3, 'Chocolate coconut energy bites are a nutritious and sweet snack. Perfect for on-the-go!', '2026-04-20', 123,
        'Kara Turner'),
       (5, 'Crispy bacon-wrapped asparagus is a savory and indulgent appetizer. A crowd-pleaser!', '2026-04-30', 124,
        'Leo Turner'),
       (4, 'Roasted garlic and herb hummus is a classic dip with a gourmet twist.', '2026-05-10', 125, 'Mila Turner'),
       (2, 'Not a fan of the tofu scramble. The texture was a bit too soft for my preference.', '2026-05-20', 126,
        'Nolan Turner'),
       (5, 'Homemade tomato basil soup is a comforting and flavorful classic. Perfect with grilled cheese!',
        '2026-05-30',
        127, 'Olive Turner'),
       (4, 'Lemon herb quinoa salad is a light and refreshing option for lunch or a side dish.', '2026-06-10', 128,
        'Percy Turner'),
       (3, 'Vegetarian zucchini lasagna is a hearty and satisfying alternative. Loved the layers of flavor.',
        '2026-06-20',
        129, 'Quinn Turner'),
       (5, 'Maple cinnamon roasted sweet potatoes are a sweet and savory side dish. A family favorite!', '2026-06-30',
        130,
        'Remy Turner');
